package com.argiintelligence.backend.advisory;

import com.argiintelligence.backend.common.exception.ApiException;
import com.argiintelligence.backend.intelligence.dto.IntelligenceReport;
import com.argiintelligence.backend.intelligence.dto.Section;
import com.argiintelligence.backend.intelligence.service.IntelligenceService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.regex.Matcher;

/**
 * AI advisory orchestration: rebuilds the farm's structured evidence server-side, asks the LLM to explain it, then
 * checks every number in the answer against that evidence. The LLM never sees raw data it could reinterpret, and the
 * decision it explains is the backend's.
 */
@Slf4j
@Service
public class AdvisoryService {

    private static final java.util.regex.Pattern NUMBER = java.util.regex.Pattern.compile("\\d[\\d,]*(?:\\.\\d+)?");
    /** Units the LLM may legitimately rescale into: thousand, lakh, million, crore. */
    private static final double[] SCALES = {1, 1e3, 1e5, 1e6, 1e7};

    private final IntelligenceService intelligenceService;
    private final GeminiAdvisoryGenerator gemini;
    private final TemplateAdvisoryGenerator template;
    private final JsonMapper jsonMapper;

    public AdvisoryService(IntelligenceService intelligenceService, GeminiAdvisoryGenerator gemini,
                           TemplateAdvisoryGenerator template, JsonMapper jsonMapper) {
        this.intelligenceService = intelligenceService;
        this.gemini = gemini;
        this.template = template;
        this.jsonMapper = jsonMapper;
    }

    /** A diagnosis previously returned by POST /api/disease/diagnose, echoed by the client. */
    public record DiseaseEvidence(@Size(max = 100) String crop, @Size(max = 200) String disease,
                                  @DecimalMin("0") @DecimalMax("1") BigDecimal probability,
                                  @Size(max = 100) String modelVersion, Boolean needsExpertReview) {
    }

    public record AdvisoryRequest(@NotNull UUID farmId, @Size(max = 100) String crop,
                                  @Pattern(regexp = "en|hi") String language, @Valid DiseaseEvidence disease) {
    }

    public record AdvisoryResponse(String language, String generatedBy, String model, boolean aiGenerated,
                                   String explanation, List<String> keyFactors, List<String> recommendedActions,
                                   List<String> uncertainty, List<String> numbersNotFoundInEvidence,
                                   String groundingNote, String fallbackReason, JsonNode evidence,
                                   String generatedAt) {
    }

    public AdvisoryResponse advise(UUID ownerId, AdvisoryRequest request) {
        String language = request.language() == null ? "en" : request.language();
        IntelligenceReport report = intelligenceService.report(ownerId, request.farmId(), request.crop());
        Map<String, Object> evidence = evidence(report, request.disease());
        String evidenceJson = jsonMapper.writeValueAsString(evidence);
        JsonNode evidenceTree = jsonMapper.readTree(evidenceJson);

        AdvisoryGenerator used = template;
        String fallbackReason = null;
        AdvisoryText text = null;
        if (gemini.available()) {
            try {
                text = gemini.generate(evidenceJson, language);
                used = gemini;
            } catch (ApiException ex) {
                fallbackReason = "Gemini call failed (" + ex.getCode() + "); showing the rule-based template instead";
            }
        } else {
            fallbackReason = "GEMINI_API_KEY is not configured; showing the rule-based template instead";
        }
        if (text == null) {
            text = template.generate(evidenceJson, language);
        }
        List<String> unverified = unverifiedNumbers(text, evidenceTree);
        boolean ai = used == gemini;
        return new AdvisoryResponse(language, used.id(), used.model(), ai, text.explanation(), text.keyFactors(),
                text.recommendedActions(), text.uncertainty(), unverified,
                ai ? "Generated by Google Gemini from the structured evidence below only; numbers are checked "
                        + "against that evidence." : "Deterministic template filled from the evidence below; not "
                        + "AI-generated.",
                fallbackReason, evidenceTree, Instant.now().toString());
    }

    /** The compact, labelled facts the LLM may use. Everything here comes from the report or the user's diagnosis. */
    static Map<String, Object> evidence(IntelligenceReport r, DiseaseEvidence disease) {
        Map<String, Object> e = new LinkedHashMap<>();
        IntelligenceReport.FarmContext f = r.farm();
        Map<String, Object> farm = new LinkedHashMap<>();
        farm.put("name", f.name());
        farm.put("state", f.state());
        farm.put("district", f.district());
        farm.put("season", f.season());
        farm.put("irrigation", f.irrigationType());
        farm.put("currentCrop", f.currentCrop());
        farm.put("soilPh", f.soilPh());
        farm.put("soilDataClassification", f.soilDataClassification());
        farm.put("areaHectares", f.areaHectares());
        e.put("farm", farm);
        e.put("focusCrop", r.focusCrop());
        e.put("focusCropReason", r.focusCropReason());
        Map<String, Object> weather = new LinkedHashMap<>();
        weather.put("status", r.weather().status());
        weather.put("source", r.weather().source());
        weather.put("dataClassification", r.weather().dataClassification());
        weather.put("current", r.weather().current());
        weather.put("next7Days", r.weather().next7Days());
        e.put("weather", weather);

        Map<String, Object> suit = new LinkedHashMap<>();
        suit.put("status", r.suitability().status());
        if (r.suitability().isOk()) {
            JsonNode s = r.suitability().data();
            List<Map<String, Object>> top = new ArrayList<>();
            for (JsonNode c : s.get("candidates")) {
                if (top.size() == 5) {
                    break;
                }
                top.add(Map.of("crop", c.get("crop").asString(), "suitabilityScore",
                        c.get("suitabilityScore").decimalValue()));
            }
            suit.put("scoreType", s.get("scoreType").asString());
            suit.put("topCandidates", top);
            JsonNode focus = IntelligenceService.candidate(r.suitability(), r.focusCrop());
            if (focus != null) {
                suit.put("focusCandidate", Map.of("crop", focus.get("crop").asString(), "suitabilityScore",
                        focus.get("suitabilityScore").decimalValue(), "evidence", focus.get("evidence")));
            }
        } else {
            suit.put("reason", r.suitability().errorMessage());
        }
        e.put("suitability", suit);

        Map<String, Object> supply = new LinkedHashMap<>();
        supply.put("status", r.supply().status());
        if (r.supply().isOk()) {
            var s = r.supply().data();
            supply.put("region", s.state());
            supply.put("cropYear", s.cropYear());
            supply.put("expectedProductionTonnes", s.forecast().expectedProductionTonnes());
            supply.put("dataClassification", s.forecast().dataClassification());
            supply.put("interval80pct", s.forecast().predictionInterval());
            supply.put("model", s.model().modelName() + " " + s.model().modelVersion());
        } else {
            supply.put("reason", r.supply().errorMessage());
        }
        e.put("supply", supply);
        e.put("demandForGapYear", demandSummary(r.demand()));
        e.put("demandOutlook", demandSummary(r.demandOutlook()));
        e.put("gap", r.gap());
        List<Map<String, Object>> anomalies = new ArrayList<>();
        for (IntelligenceReport.AnomalyCheck a : r.anomalies()) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("label", a.label());
            m.put("status", a.result().isOk() ? a.result().data().get("status").asString() : "UNAVAILABLE");
            if (a.result().isOk()) {
                JsonNode d = a.result().data();
                m.put("period", d.get("period").asString());
                m.put("direction", d.get("direction").asString());
                m.put("observedValue", d.get("observedValue").decimalValue());
                m.put("baselineMedian", d.get("baseline").isNull() ? null : d.get("baseline").decimalValue());
            }
            anomalies.add(m);
        }
        e.put("anomalies", anomalies);
        e.put("risk", r.risk());
        e.put("decision", r.decision());
        if (disease != null && disease.disease() != null) {
            Map<String, Object> d = new LinkedHashMap<>();
            d.put("crop", disease.crop());
            d.put("disease", disease.disease());
            d.put("probability", disease.probability());
            d.put("modelVersion", disease.modelVersion());
            d.put("needsExpertReview", disease.needsExpertReview());
            d.put("note", "image classification from a PlantVillage-trained model; uncalibrated probability");
            e.put("disease", d);
        }
        e.put("dataNotices", r.dataNotices());
        return e;
    }

    private static Map<String, Object> demandSummary(Section<JsonNode> s) {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("status", s.status());
        if (s.isOk()) {
            JsonNode d = s.data();
            m.put("region", d.get("region").asString());
            m.put("period", d.get("period").asString());
            m.put("valueTonnes", d.get("forecast").decimalValue());
            m.put("dataClassification", d.get("dataClassification").asString());
            m.put("method", d.get("method").asString());
            m.put("interval", d.get("interval"));
        } else {
            m.put("reason", s.errorMessage());
        }
        return m;
    }

    /**
     * Numbers in the generated text that match no evidence number (within 2 %, allowing rescaling to thousand/lakh/
     * million/crore). Small integers (< 10) are ignored: they are usually counts such as "3 steps".
     */
    static List<String> unverifiedNumbers(AdvisoryText text, JsonNode evidence) {
        List<Double> known = new ArrayList<>();
        collect(evidence, known);
        List<String> out = new ArrayList<>();
        List<String> parts = new ArrayList<>();
        parts.add(text.explanation());
        parts.addAll(text.keyFactors());
        parts.addAll(text.recommendedActions());
        parts.addAll(text.uncertainty());
        for (String p : parts) {
            Matcher m = NUMBER.matcher(p == null ? "" : p);
            while (m.find()) {
                String token = m.group();
                double v;
                try {
                    v = Double.parseDouble(token.replace(",", ""));
                } catch (NumberFormatException ex) {
                    continue;
                }
                if (v < 10 || grounded(v, known)) {
                    continue;
                }
                if (!out.contains(token)) {
                    out.add(token);
                }
            }
        }
        return out;
    }

    private static boolean grounded(double v, List<Double> known) {
        for (double k : known) {
            for (double scale : SCALES) {
                double scaled = v * scale;
                double ak = Math.abs(k);
                if (ak == 0 ? scaled == 0 : Math.abs(scaled - ak) / ak <= 0.02) {
                    return true;
                }
                // Percentages written as fractions or vice versa.
                if (ak > 0 && ak <= 1 && Math.abs(v / 100 - ak) / ak <= 0.02) {
                    return true;
                }
            }
        }
        return false;
    }

    private static void collect(JsonNode n, List<Double> out) {
        if (n == null) {
            return;
        }
        if (n.isNumber()) {
            out.add(n.asDouble());
        } else if (n.isString()) {
            Matcher m = NUMBER.matcher(n.asString());
            while (m.find()) {
                try {
                    out.add(Double.parseDouble(m.group().replace(",", "")));
                } catch (NumberFormatException ignored) {
                    // not a number after all
                }
            }
        } else if (n.isContainer()) {
            n.forEach(c -> collect(c, out));
        }
    }
}
